//! Build script: reads `SUPABASE_URL` / `SUPABASE_ANON_KEY` from the
//! environment and writes them into `$OUT_DIR/supabase_config.rs` so they
//! are available at compile time.  Cargo automatically re-runs this script
//! when those env vars change, ensuring `trunk serve` picks up new values
//! without needing `cargo clean`.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-env-changed=SUPABASE_URL");
    println!("cargo:rerun-if-env-changed=SUPABASE_ANON_KEY");

    let url = std::env::var("SUPABASE_URL").unwrap_or_default();
    let anon = std::env::var("SUPABASE_ANON_KEY").unwrap_or_default();

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let dest = std::path::Path::new(&out_dir).join("supabase_config.rs");

    let content = format!(
        "// Generated by build.rs. Do not edit.\n\
         pub const SUPABASE_URL: &str = {url:?};\n\
         pub const SUPABASE_ANON_KEY: &str = {anon:?};\n",
    );

    std::fs::write(&dest, content).expect("failed to write supabase_config.rs");
}
