[build]
target = "index.html"
release = true
dist = "dist"
public_url = "/"
filehash = true
inject_scripts = true
minify = "on_release"
no_sri = false
cross_origin = ""

[watch]
watch = []
ignore = []

[serve]
addresses = ["127.0.0.1"]
port = 3000
open = false
no_autoreload = false
no_error_reporting = false
no_spa = false
